name: CI

on: [push]

jobs:
  web-deploy:
    name: HTML-validator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2 
      - name: Test Files # https://github.com/marketplace/actions/html5-validator
        uses: Cyb3r-Jak3/html5validator-action@v0.6.1 
        with:
          root: ./source/
  codacy-analysis-cli:
    name: Codacy Analysis CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
          
